### PR TITLE
docs: fix lint update CONTRIBUTING.md

### LINKED ISSUE #631: Bug: Test Version Release
### What happened?

Test Version Release

### What did you expect to happen?

Test Version Release

### How can we reproduce it (as minimally and precisely as possible)?

Test Version Release

### Anything else we need to know?

_No response_

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

### PR DESCRIPTION
**Pull request by EthanForAi**
#### 🔍 What type of PR is this?
/kind bug

#### 👀 What this PR does / why we need it:

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

#### 🅰 Which issue(s) this PR fixes:

Fixes #631

### CODE REVIEW

**Comment by EthanForAi** [comment]
The signature to be committed in order to sign the CLA

**Comment by EthanForAi** [comment]
The signature to be committed in order to sign the CLA

**Comment by EthanForAi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by cubxxw — APPROVED** [review]

**Review by skiffer-git — APPROVED** [review]

**Comment by cubxxw** [comment]
cherry-pick

**Pull request merged**
