### PR TITLE
Release/v3.1 merge

### PR DESCRIPTION
**Pull request by cubxxw**
<br>

#### 🔍 What type of PR is this?
/kind documentation
/kind feature

Fixes OpenIMSDK/Open-IM-Server#720

### CODE REVIEW

**Comment by skiffer-git** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by cubxxw** [comment]
#720

**Comment by cubxxw** [comment]
recheck

**Comment by cubxxw** [comment]
https://github.com/OpenIMSDK/Open-IM-Server/issues/720

**Pull request merged**
