### PR TITLE
fix: #2888 sort import modules

### LINKED ISSUE #2888: [BUG] module imports are not sorted
### OpenIM Server Version

v3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

I think it would help to understand code better, maintain easily, if imports are sorted in order like std, third packages, privated packages from current module,

could I send a PR to fulfill this request?

### Screenshots Link

_No response_

### PR DESCRIPTION
**Pull request by morya**
## 🅰 Please add the issue ID after "Fixes #"

Fixes #2888

### CODE REVIEW

**Review by icey-yu — APPROVED** [review]

**Comment by mo3et** [comment]
I suggest use [goimports](https://pkg.go.dev/golang.org/x/tools/cmd/goimports) solve this problem.

Because the issue is from no category pkg to categoried. Use this tools is no good for maintain. But this issue need to be solve.

Plz use goimports.

**Comment by morya** [comment]
already discussed with @Whyyyyy , he agreed this, so, should I switch back to goimports?

**Comment by morya** [comment]
> already discussed with @Whyyyyy , he agreed this, so, should I switch back to goimports?

goimports won't merge all same kind imports into one group,

```go
import (
	"context"
	"fmt"
	"github.com/openimsdk/open-im-server/v3/pkg/common/config"
	"github.com/openimsdk/tools/utils/datautil"
	"github.com/openimsdk/tools/utils/network"
	"net"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	kdisc "github.com/openimsdk/open-im-server/v3/pkg/common/discoveryregister"
	"github.com/openimsdk/open-im-server/v3/pkg/common/prommetrics"
	"github.com/openimsdk/tools/discovery"
	"github.com/openimsdk/tools/errs"
	"github.com/openimsdk/tools/log"
	"github.com/openimsdk/tools/system/program"
)
```

become 

```go
import (
	"context"
	"fmt"



	"net"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	// separated group
	"github.com/openimsdk/open-im-server/v3/pkg/common/config"
	"github.com/openimsdk/tools/utils/datautil"
	"github.com/openimsdk/tools/utils/network"

	kdisc "github.com/openimsdk/open-im-server/v3/pkg/common/discoveryregister"
	"github.com/openimsdk/open-im-server/v3/pkg/common/prommetrics"
	"github.com/openimsdk/tools/discovery"
	"github.com/openimsdk/tools/errs"
	"github.com/openimsdk/tools/log"
	"github.com/openimsdk/tools/system/program"
)
```

**Comment by mo3et** [comment]
> already discussed with @Whyyyyy , he agreed this, so, should I switch back to goimports?

I talk the reason in before reply. Use CLI tools is no good to the maintain. 

I think just need spilt the local module and third module that is fine.

**Pull request closed without merging**
