### PR TITLE
Update cla.yml

### LINKED ISSUE #633: feature: add cra
feature: add cra

### PR DESCRIPTION
**Pull request by kubbot**
#### 🔍 What type of PR is this?
/kind bug

#### 👀 What this PR does / why we need it:

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

#### 🅰 Which issue(s) this PR fixes:

Fixes #633

### CODE REVIEW

**Review by skiffer-git — APPROVED** [review]

**Review by cubxxw — APPROVED** [review]

**Comment by cubxxw** [comment]
rebase

**Pull request merged**
