### PR TITLE
docs：添加 CONTRIBUTING_zh-CN.md

### PR DESCRIPTION
**Pull request by SwardHorse**
添加了 CONTRIBUTING_zh-CN.md，同时发现了原文中的几个链接是404，可以检查并加以修复正确的网址

### CODE REVIEW

**Comment by cubxxw** [comment]
I'm glad to see your pr. I have a few questions. You mentioned that there are several empty links in the contributor document. Can you optimize this pr based on the contributor documentation, such as naming conventions, where multiple commit rebases become one?

**Review by cubxxw — CHANGES_REQUESTED** [review]
Use git rebase

**Comment by SwardHorse** [comment]
git rebased
有问题的网址：
行为准则 - [PR] [RFC]
目前检查到的就是这两个链接，在文章中多次出现，均有问题

**Comment by SwardHorse** [comment]
sorry i don't really understand , this is my first PR , is that mean my "CONTRIBUTING_zh.md" need to PR in https://github.com/OpenIMSDK/community rather than Open-IM-Server?

**Comment by cubxxw** [comment]
> sorry i don't really understand , this is my first PR , is that mean my "CONTRIBUTING_zh.md" need to PR in [OpenIMSDK/community](https://github.com/OpenIMSDK/community) rather than Open-IM-Server?
Yes, that's the idea. The Open-IM-Server repository can provide Chinese README.md documentation and improve our English documentation CONTRIBUTING, which has been mentioned in the issue. You can transfer this PR to OpenIMSDK/community

**Pull request closed without merging**
