### PR TITLE
fix bug:invalid go version '1.21.2' : must match format 1.23

### LINKED ISSUE #2229: [BUG] fix bug:invalid go version '1.21.2' : must match format 1.23
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

fix bug:invalid go version '1.21.2' : must match format 1.23

### Screenshots Link

_No response_

### PR DESCRIPTION
**Pull request by AerisVibe**
<br>

#### 👀 What this PR does / why we need it:

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

#### 🅰 Which issue(s) this PR fixes:

Fixes #2229

### CODE REVIEW

**Comment by AerisVibe** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by cubxxw** [comment]
recheck

**Comment by skiffer-git** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AerisVibe** [comment]
recheck

**Comment by AerisVibe** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by cubxxw** [comment]
@AerisVibe You need to use the @fx10007 account of the committer in https://github.com/openimsdk/open-im-server/pull/2228/commits to sign the CLA, as the PR submitter and commit author do not currently match.

**Pull request closed without merging**
