### PR TITLE
fix Details

### PR DESCRIPTION
**Pull request by dgqypl**
1. Unify the receiver of structure methods and use pointer
2. Use errors.Is to make error judgments
3. Fix word spelling errors

### CODE REVIEW

**Comment by dgqypl** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dgqypl** [comment]
recheck

**Comment by dgqypl** [comment]
> 💕 Thank you for your contribution and please kindly read and sign our [CLA Docs](https://github.com/OpenIM-Robot/cla/blob/main/README.md)
> 
> The signature to be committed in order to sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request. Posted by the **CLA Assistant Lite bot**.

recheck

**Comment by dgqypl** [comment]
recheck

**Comment by mo3et** [comment]
recheck

**Review by mo3et — APPROVED** [review]

**Review by FGadvancer — APPROVED** [review]

**Pull request merged**
