### PR TITLE
docs: fix english typo

### PR DESCRIPTION
**Pull request by totalo**

### CODE REVIEW

**Comment by totalo** [comment]
> **CLA Assistant Lite bot:** 💕 Thank you for your contribution and please kindly read and sign our [🎯https://github.com/openim-sigs/cla/blob/main/README.md](https://github.com/openim-sigs/cla/blob/main/README.md). CLA Assistant Lite 机器人：💕感谢您的贡献，请阅读并签署我们的 🎯https://github.com/openim-sigs/cla/blob/main/README.md。 If you wish to sign the CRA, **Please copy and comment on the following sentence:**如果您想签署 CRA，请复制并评论以下句子：
> 
> I have read the CLA Document and I hereby sign the CLA我已阅读 CLA 文件，并特此签署 CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request



> I have read the CLA Document and I hereby sign the CLA

I have read the CLA Document and I hereby sign the CLA

**Comment by totalo** [comment]
> **CLA Assistant Lite bot:** 💕 Thank you for your contribution and please kindly read and sign our [🎯https://github.com/openim-sigs/cla/blob/main/README.md](https://github.com/openim-sigs/cla/blob/main/README.md). If you wish to sign the CRA, **Please copy and comment on the following sentence:**
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request



> **CLA Assistant Lite bot:** 💕 Thank you for your contribution and please kindly read and sign our [🎯https://github.com/openim-sigs/cla/blob/main/README.md](https://github.com/openim-sigs/cla/blob/main/README.md). If you wish to sign the CRA, **Please copy and comment on the following sentence:**
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the CLA Document and I hereby sign the CLA

**Comment by totalo** [comment]
> **CLA Assistant Lite bot:** 💕 Thank you for your contribution and please kindly read and sign our [🎯https://github.com/openim-sigs/cla/blob/main/README.md](https://github.com/openim-sigs/cla/blob/main/README.md). If you wish to sign the CRA, **Please copy and comment on the following sentence:**
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the CLA Document and I hereby sign the CLA

**Comment by totalo** [comment]
recheck

**Comment by totalo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by totalo** [comment]
recheck

**Review by FGadvancer — APPROVED** [review]

**Review by withchao — APPROVED** [review]

**Pull request merged**
