### PR TITLE
feat: remove redundant read deadline in gateway

### LINKED ISSUE #1028: Bug: gateway redundant set read deadline
### What happened?

截屏2023-09-07 11 33 04

it has set conn read deadline, but when received binary message, it reset it again which is unnecessary.

### What did you expect to happen?

remove the read deadline when enter binary message case

### How can we reproduce it (as minimally and precisely as possible)?

it is optimization operation, you can output read deadline time

### Anything else we need to know?

_No response_

### version

<details>
```console
$ open im server version
# v3.2.2-alpha.0-24-g2cca15d7c
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

### PR DESCRIPTION
**Pull request by charlie-bit**
<br>

#### 👀 What this PR does / why we need it:

- [X] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [X] All the tests have passed

 remove redundant set read deadline, it has set for conn before.

#### 🅰 Which issue(s) this PR fixes:

Fixes #1028

### CODE REVIEW

**Comment by charlie-bit** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by cubxxw** [comment]
recheck

**Review by cubxxw — APPROVED** [review]

**Comment by cubxxw** [comment]
LGTM 
bug u need [https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal[…]il-preferences/adding-an-email-address-to-your-github-account](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account)

**Comment by charlie-bit** [comment]
recheck

**Review by cubxxw — APPROVED** [review]

**Comment by FGadvancer** [comment]
The client currently relies on the combination of obtaining the sequence number and heartbeat functionality. Removing this line of code could potentially result in the inability to receive messages promptly when there is no network connection.

**Comment by cubxxw** [comment]
Link https://github.com/openimsdk/open-im-server/pull/1036

**Pull request merged**
